# Site settings
name: JM的博客
email: 471938302@qq.com
author: JM
url: https://www.jmazm.com
resume_site: http://www.jmazm.com/effects/demo/demo-font-end-resume/index.html
github: https://github.com/JMHello/
baseurl: ""  #根目录
description: Believe yourself! The future belongs to you!
motto: Enjoy life!
#motto: 如果生活欺骗了你，不要悲伤，不要哭泣。
banner:  笑对人生，相信自己。
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: JMHello
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : jm
