-- MySQL Script generated by MySQL Workbench
-- Tue Jan 30 14:42:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tiantiantao
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tiantiantao` ;

-- -----------------------------------------------------
-- Schema tiantiantao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tiantiantao` DEFAULT CHARACTER SET utf8 ;
USE `tiantiantao` ;

-- -----------------------------------------------------
-- Table `tiantiantao`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`User` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`User` (
  `idUser` INT NOT NULL,
  `account` VARCHAR(26) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `sex` TINYINT(1) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(13) NOT NULL,
  `avatarUrl` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  UNIQUE INDEX `account_UNIQUE` (`account` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`Admin` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`Admin` (
  `idAdmin` INT NOT NULL,
  `account` VARCHAR(26) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdmin`),
  UNIQUE INDEX `idAdmin_UNIQUE` (`idAdmin` ASC),
  UNIQUE INDEX `account_UNIQUE` (`account` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`GoodsType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`GoodsType` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`GoodsType` (
  `idGoodsType` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `isUsed` TINYINT(1) NULL DEFAULT NULL,
  `GoodsType_idGoodsType` INT NOT NULL,
  PRIMARY KEY (`idGoodsType`),
  INDEX `fk_GoodsType_GoodsType_idx` (`GoodsType_idGoodsType` ASC),
  CONSTRAINT `fk_GoodsType_GoodsType`
    FOREIGN KEY (`GoodsType_idGoodsType`)
    REFERENCES `tiantiantao`.`GoodsType` (`idGoodsType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`Brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`Brand` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`Brand` (
  `idBrand` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `shortName` VARCHAR(45) NULL DEFAULT NULL,
  `websiteUrl` VARCHAR(45) NULL DEFAULT NULL,
  `imageUrl` VARCHAR(200) NULL DEFAULT NULL,
  `isFeatured` TINYINT(1) NOT NULL,
  `isUsed` TINYINT(1) NOT NULL,
  `GoodsType_idGoodsType` INT NOT NULL,
  PRIMARY KEY (`idBrand`),
  UNIQUE INDEX `idBrand_UNIQUE` (`idBrand` ASC),
  INDEX `fk_Brand_GoodsType1_idx` (`GoodsType_idGoodsType` ASC),
  CONSTRAINT `fk_Brand_GoodsType1`
    FOREIGN KEY (`GoodsType_idGoodsType`)
    REFERENCES `tiantiantao`.`GoodsType` (`idGoodsType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`Specification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`Specification` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`Specification` (
  `idSpecification` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `GoodsType_idGoodsType` INT NOT NULL,
  PRIMARY KEY (`idSpecification`),
  UNIQUE INDEX `idSpecification_UNIQUE` (`idSpecification` ASC),
  INDEX `fk_Specification_GoodsType1_idx` (`GoodsType_idGoodsType` ASC),
  CONSTRAINT `fk_Specification_GoodsType1`
    FOREIGN KEY (`GoodsType_idGoodsType`)
    REFERENCES `tiantiantao`.`GoodsType` (`idGoodsType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`SpecificationDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`SpecificationDetail` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`SpecificationDetail` (
  `idSpecificationDetail` INT NOT NULL,
  `value` VARCHAR(45) NULL DEFAULT NULL,
  `Specification_idSpecification` INT NOT NULL,
  PRIMARY KEY (`idSpecificationDetail`),
  UNIQUE INDEX `idSpecificationDetail_UNIQUE` (`idSpecificationDetail` ASC),
  INDEX `fk_SpecificationDetail_Specification1_idx` (`Specification_idSpecification` ASC),
  CONSTRAINT `fk_SpecificationDetail_Specification1`
    FOREIGN KEY (`Specification_idSpecification`)
    REFERENCES `tiantiantao`.`Specification` (`idSpecification`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`Goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`Goods` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`Goods` (
  `idGoods` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `GoodsType_idGoodsType` INT NOT NULL,
  `Brand_idBrand` INT NOT NULL,
  PRIMARY KEY (`idGoods`),
  UNIQUE INDEX `idGoods_UNIQUE` (`idGoods` ASC),
  INDEX `fk_Goods_GoodsType1_idx` (`GoodsType_idGoodsType` ASC),
  INDEX `fk_Goods_Brand1_idx` (`Brand_idBrand` ASC),
  CONSTRAINT `fk_Goods_GoodsType1`
    FOREIGN KEY (`GoodsType_idGoodsType`)
    REFERENCES `tiantiantao`.`GoodsType` (`idGoodsType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Goods_Brand1`
    FOREIGN KEY (`Brand_idBrand`)
    REFERENCES `tiantiantao`.`Brand` (`idBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`GoodsDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`GoodsDetail` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`GoodsDetail` (
  `idGoodsDetail` INT NOT NULL,
  `isDefault` TINYINT(1) NULL DEFAULT 0,
  `specification` VARCHAR(45) NULL DEFAULT NULL,
  `weight` FLOAT NULL DEFAULT 0.00,
  `stock` INT(10) NULL DEFAULT 0,
  `hasPurchasedQuantity` INT(10) NULL DEFAULT 0,
  `originalPrice` FLOAT NULL DEFAULT 0.00,
  `activityPrice` FLOAT NULL DEFAULT 0.00,
  `discountPrice` FLOAT NULL DEFAULT 0.00,
  `Goods_idGoods` INT NOT NULL,
  PRIMARY KEY (`idGoodsDetail`),
  UNIQUE INDEX `idGoodsDetail_UNIQUE` (`idGoodsDetail` ASC),
  INDEX `fk_GoodsDetail_Goods1_idx` (`Goods_idGoods` ASC),
  CONSTRAINT `fk_GoodsDetail_Goods1`
    FOREIGN KEY (`Goods_idGoods`)
    REFERENCES `tiantiantao`.`Goods` (`idGoods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`ShippingAddress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`ShippingAddress` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`ShippingAddress` (
  `idShippingAddress` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(13) NULL DEFAULT NULL,
  `postalCode` DECIMAL NULL DEFAULT NULL,
  `address` VARCHAR(20) NULL DEFAULT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idShippingAddress`),
  UNIQUE INDEX `idShippingAddress_UNIQUE` (`idShippingAddress` ASC),
  INDEX `fk_ShippingAddress_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_ShippingAddress_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `tiantiantao`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`Order` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`Order` (
  `idOrder` INT NOT NULL,
  `orderStatus` TINYINT(1) NULL DEFAULT NULL,
  `time` DATETIME NULL DEFAULT NULL,
  `paymentStatus` TINYINT(1) NULL DEFAULT NULL,
  `paymentMethod` VARCHAR(45) NULL DEFAULT NULL,
  `deliveryStatus` TINYINT(1) NULL DEFAULT NULL,
  `deliveryMethod` VARCHAR(45) NULL DEFAULT NULL,
  `recipientInfo` VARCHAR(255) NULL DEFAULT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idOrder`),
  UNIQUE INDEX `idOrder_UNIQUE` (`idOrder` ASC),
  INDEX `fk_Order_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Order_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `tiantiantao`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`OrderDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`OrderDetail` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`OrderDetail` (
  `idOrderDetail` INT NOT NULL,
  `quantity` FLOAT NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `Order_idOrder` INT NOT NULL,
  `Goods_idGoods` INT NOT NULL,
  PRIMARY KEY (`idOrderDetail`),
  UNIQUE INDEX `idOrderDetail_UNIQUE` (`idOrderDetail` ASC),
  INDEX `fk_OrderDetail_Order1_idx` (`Order_idOrder` ASC),
  INDEX `fk_OrderDetail_Goods1_idx` (`Goods_idGoods` ASC),
  CONSTRAINT `fk_OrderDetail_Order1`
    FOREIGN KEY (`Order_idOrder`)
    REFERENCES `tiantiantao`.`Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderDetail_Goods1`
    FOREIGN KEY (`Goods_idGoods`)
    REFERENCES `tiantiantao`.`Goods` (`idGoods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`Banner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`Banner` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`Banner` (
  `idBanner` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `imageUrl` VARCHAR(200) NULL DEFAULT NULL,
  `websiteUrl` VARCHAR(45) NULL DEFAULT NULL,
  `Admin_idAdmin` INT NOT NULL,
  PRIMARY KEY (`idBanner`),
  UNIQUE INDEX `idBanner_UNIQUE` (`idBanner` ASC),
  INDEX `fk_Banner_Admin1_idx` (`Admin_idAdmin` ASC),
  CONSTRAINT `fk_Banner_Admin1`
    FOREIGN KEY (`Admin_idAdmin`)
    REFERENCES `tiantiantao`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`GoodsImage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`GoodsImage` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`GoodsImage` (
  `idGoodsImage` INT NOT NULL,
  `imageUrl` VARCHAR(200) NULL DEFAULT NULL,
  `Goods_idGoods` INT NOT NULL,
  PRIMARY KEY (`idGoodsImage`),
  UNIQUE INDEX `idGoodsImage_UNIQUE` (`idGoodsImage` ASC),
  INDEX `fk_GoodsImage_Goods1_idx` (`Goods_idGoods` ASC),
  CONSTRAINT `fk_GoodsImage_Goods1`
    FOREIGN KEY (`Goods_idGoods`)
    REFERENCES `tiantiantao`.`Goods` (`idGoods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`Suggestion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`Suggestion` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`Suggestion` (
  `idSuggestion` INT NOT NULL,
  `suggestion` VARCHAR(255) NULL DEFAULT NULL,
  `reply` VARCHAR(255) NULL DEFAULT NULL,
  `Admin_idAdmin` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idSuggestion`),
  INDEX `fk_Suggestion_Admin1_idx` (`Admin_idAdmin` ASC),
  INDEX `fk_Suggestion_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Suggestion_Admin1`
    FOREIGN KEY (`Admin_idAdmin`)
    REFERENCES `tiantiantao`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Suggestion_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `tiantiantao`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`ShoppingCart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`ShoppingCart` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`ShoppingCart` (
  `idShoppingCart` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idShoppingCart`),
  UNIQUE INDEX `idShoppingCart_UNIQUE` (`idShoppingCart` ASC),
  INDEX `fk_ShoppingCart_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_ShoppingCart_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `tiantiantao`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`ShoppingCartDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`ShoppingCartDetail` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`ShoppingCartDetail` (
  `idShoppingCartDetail` INT NOT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `time` DATETIME NULL DEFAULT NULL,
  `ShoppingCart_idShoppingCart` INT NOT NULL,
  `Goods_idGoods` INT NOT NULL,
  PRIMARY KEY (`idShoppingCartDetail`),
  UNIQUE INDEX `idShoppingCartDetail_UNIQUE` (`idShoppingCartDetail` ASC),
  INDEX `fk_ShoppingCartDetail_ShoppingCart1_idx` (`ShoppingCart_idShoppingCart` ASC),
  INDEX `fk_ShoppingCartDetail_Goods1_idx` (`Goods_idGoods` ASC),
  CONSTRAINT `fk_ShoppingCartDetail_ShoppingCart1`
    FOREIGN KEY (`ShoppingCart_idShoppingCart`)
    REFERENCES `tiantiantao`.`ShoppingCart` (`idShoppingCart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ShoppingCartDetail_Goods1`
    FOREIGN KEY (`Goods_idGoods`)
    REFERENCES `tiantiantao`.`Goods` (`idGoods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`Collection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`Collection` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`Collection` (
  `idCollection` INT NOT NULL,
  `time` DATETIME NULL DEFAULT NULL,
  `User_idUser` INT NOT NULL,
  `Goods_idGoods` INT NOT NULL,
  PRIMARY KEY (`idCollection`),
  INDEX `fk_Collection_User1_idx` (`User_idUser` ASC),
  INDEX `fk_Collection_Goods1_idx` (`Goods_idGoods` ASC),
  CONSTRAINT `fk_Collection_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `tiantiantao`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Collection_Goods1`
    FOREIGN KEY (`Goods_idGoods`)
    REFERENCES `tiantiantao`.`Goods` (`idGoods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
